repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev:  v8.18.2
    hooks:
      - id: gitleaks-docker
        name: Detect hardcoded secrets
        description: Detect hardcoded secrets using Gitleaks
        entry: zricethezav/gitleaks protect --verbose --redact --staged
        language: docker_image