name: simple-app

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/simple_app:latest
          build-args: VERSION=${{ env.VERSION }}

       -  name: Set up environment
          run: |
            # Retrieve the current version from an environment variable
            CURRENT_VERSION=$VERSION

            # Split the version number into its components
            IFS='.' read -r -a VERSION_PARTS <<< "$CURRENT_VERSION"

            # Increment the last part of the version number
            NEW_VERSION="${VERSION_PARTS[0]}.${VERSION_PARTS[1]}.$((${VERSION_PARTS[2]} + 1))"

            echo "New version number: $NEW_VERSION"

            # Set the new version number as an output variable
            echo "::set-output name=new_version::$NEW_VERSION"

      - name: Use the new version
        run: |
          echo "The new version is ${{ steps.setup.outputs.new_version }}"


  