name: simple-app

on:
  push:
    branches:
      - "master"

jobs:
  build_and_delivery:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4

      - 
        name: Download Dependency-Check CLI
        run: |
          wget https://dl.bintray.com/jeremy-long/owasp/dependency-check-7.0.0-release.zip -O dependency-check-7.0.0-release.zip
          ls -l  # Check if the file is downloaded
          unzip -q dependency-check-7.0.0-release.zip -d dependency-check



      - 
        name: Run Dependency-Check
        run: |
          ./dependency-check/bin/dependency-check.sh --scan ./target --project "Your Project Name" --format JSON

      - 
        name: Parse Dependency-Check Report
        run: |
          CRITICAL_VULNERABILITIES=$(jq '.dependencies[] | select(.vulnerabilities[].severity == "Critical")' dependency-check-report.json)
          if [ ! -z "$CRITICAL_VULNERABILITIES" ]; then
            echo "Critical vulnerabilities found, failing the pipeline."
            exit 1
          fi
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/simple_app:${{ vars.VERSION }}
          build-args: VERSION=${{ vars.VERSION }}


  increment_version:
    runs-on: ubuntu-latest
    needs: build_and_delivery
    if: ${{ success() }}
    steps:
    - name: version increanent
      uses: action-pack/increment@v2
      with:
        name: 'VERSION'
        token: ${{ secrets.REPO_ACCESS_TOKEN }}    
        

  