name: simple-app

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/simple_app:latest
          build-args: VERSION=${{ env.VERSION }}

      # - name: Set up environment
      #   run: |
      #     # Extract the current version from your environment variable
      #     CURRENT_VERSION=${{ env.VERSION }}

      #     # Split the version string into its components
      #     IFS='.' read -r -a VERSION_PARTS <<< "$CURRENT_VERSION"

      #     # Increment the patch version (last part of the version)
      #     ((VERSION_PARTS[2]++))

      #     # Combine the version parts back into a string
      #     NEW_VERSION="${VERSION_PARTS[0]}.${VERSION_PARTS[1]}.${VERSION_PARTS[2]}"

      #     # Set the new version back to the environment variable
      #     echo "VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Display new version
        run: echo "New version is ${{ env.VERSION }}"

  